import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BarRange from '../components/BarRange'

export default function Home() {
 
  return (
    <>
      <Head>
        <title>Proxyrack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
           <div className={styles.container}>
             <div className={styles.heading}>
               <h2>Only pay for what you need</h2>
               <p>And get 3x what other proxy providers give you.</p>
             </div>
             <div className={styles.pay_filter}>
                <BarRange />
             </div>
           </div>
      </main>
    </>
  )
}
